In [2]:
import sys
import os

sys.path.append(os.path.join(os.getcwd(),'../code'))

In [3]:
from util import load_shop_odds
import numpy as np

shop = load_shop_odds()
# np.sum(shop[1])
shop

[array([1., 0., 0., 0., 0., 0.]),
 array([1., 0., 0., 0., 0., 0.]),
 array([0.75, 0.25, 0.  , 0.  , 0.  , 0.  ]),
 array([0.55, 0.3 , 0.15, 0.  , 0.  , 0.  ]),
 array([0.45, 0.33, 0.2 , 0.02, 0.  , 0.  ]),
 array([0.3 , 0.4 , 0.25, 0.05, 0.  , 0.  ]),
 array([0.19, 0.3 , 0.4 , 0.1 , 0.01, 0.  ]),
 array([0.18, 0.25, 0.32, 0.22, 0.03, 0.  ]),
 array([0.15, 0.2 , 0.25, 0.3 , 0.1 , 0.  ]),
 array([0.05, 0.1 , 0.2 , 0.4 , 0.25, 0.  ]),
 array([0.01, 0.02, 0.12, 0.5 , 0.35, 0.  ])]

In [4]:
from Pool import Pool 

pool = Pool()
print(pool.size())



1198


In [5]:
from Shop import Shop

shop = Shop(7)

shop.fresh_shop(pool)

pool.size()



1193

In [6]:
from Unit import Unit

pool.get_odds(Unit('Violet', 1))

0.07159904534606205

In [7]:
pool.get_unit(5)

In [8]:
shop.get_odds(Unit('Smeech', 3), pool)

0.031034482758620693

In [9]:
shop.fresh_shop(pool)
print(pool.size())

shop.fresh_shop(pool)
shop.shop_names()
print(pool.size())

1187
1182


In [10]:
shop.refresh_shop(pool)

print(shop.shop_names())

print(pool.size())

shop.refresh_shop(pool)

print(shop.shop_names())

print(pool.size())

shop.refresh_shop(pool)

print(shop.shop_names())

print(pool.size())

['Darius', 'Gangplank', 'Akali', 'Nunu & Willump', 'Steb']
1182
['Loris', 'Twisted Fate', "Kog'Maw", 'Zoe', 'Cassiopeia']
1182
['Ziggs', 'Gangplank', 'Camille', 'Ezreal', 'Sett']
1182


In [11]:
pool.size(3)

229

In [22]:
from util import number_shops

number_shops(Unit("Jinx",5), nteam=0, npool=pool.size(5)-4, nother=0, star=1,level=8, shop=shop)

Probability per shop slot for hitting 1 Jinxs per: 
[0.004029850746268657]
Expected number of shop slots to hit 1 Jinxs per: 
[248.14814814814815]
Expected total number of shop slots to hit 1 Jinxs: 
248.14814814814815
Expected total number of shops to hit 1 Jinxs: 
49.62962962962963


[248.14814814814815]

In [7]:
nteam = 2

n_needed = 3 - nteam % 3
n_needed

1