In [1]:
from util import load_shop_odds

load_shop_odds()

{'level': 1, 'dropRatesByTier': [{'cost': 1, 'rate': 100}, {'cost': 2, 'rate': 0}, {'cost': 3, 'rate': 0}, {'cost': 4, 'rate': 0}, {'cost': 5, 'rate': 0}, {'cost': 6, 'rate': 0}]}


[array([100,   0,   0,   0,   0,   0]),
 array([100,   0,   0,   0,   0,   0]),
 array([75, 25,  0,  0,  0,  0]),
 array([55, 30, 15,  0,  0,  0]),
 array([45, 33, 20,  2,  0,  0]),
 array([30, 40, 25,  5,  0,  0]),
 array([19, 30, 40, 10,  1,  0]),
 array([18, 25, 32, 22,  3,  0]),
 array([15, 20, 25, 30, 10,  0]),
 array([ 5, 10, 20, 40, 25,  0]),
 array([ 1,  2, 12, 50, 35,  0])]

In [4]:
import numpy as np

np.random.choice([1,2,3])

1

In [5]:
from Pool import Pool 

pool = Pool()
print(pool.size())



1092


In [6]:
from Shop import Shop

shop = Shop(7)

shop.fresh_shop(pool)

pool.size()



1087

In [7]:
pool.get_odds(Unit('Milio', 1))

0.08357348703170028

In [8]:
pool.get_unit(5)

In [9]:
shop.get_odds(Unit('Darius', 3), pool)

0.027155172413793102

In [10]:
shop.fresh_shop(pool)
print(pool.size())

shop.fresh_shop(pool)
shop.shop_names()
print(pool.size())

1081
1076


In [11]:
shop.refresh_shop(pool)

print(shop.shop_names())

print(pool.size())

shop.refresh_shop(pool)

print(shop.shop_names())

print(pool.size())

shop.refresh_shop(pool)

print(shop.shop_names())

print(pool.size())

['Kassadin', 'Ryze', "Kai'Sa", 'Renekton', 'Vi']
1076
['Naafiri', 'Fiora', 'Mordekaiser', "Vel'Koz", "Kai'Sa"]
1076
['Poppy', 'Quinn', 'Katarina', 'Milio', 'Azir']
1076


In [15]:
pool.size(3)

229

In [37]:
from util import number_shops

number_shops(Unit("Fiora",4), nteam=0, npool=pool.size(4)-5, nother=1, star=2,level=8)

[0.020072992700729927, 0.01838235294117647, 0.016666666666666666]
[49.81818181818182, 54.4, 60.0]
164.21818181818182
32.843636363636364
